import { Camaro, Corolla } from "@/assets/imageIndex";

export const MODE = {
  ON_TOUCH: "onTouched",
} as const;

export const SEARCH_CONFIG = {
  PAGE_SIZE: 12,
  SKELETON_COUNT: 6,
  SKELETON_IDS: Array.from({ length: 6 }, (_, i) => `skeleton-${i}`),
} as const;

export const MESSAGES = {
  signUpSuccess: "Enter the verification code we sent to your phone.",
  signInSuccess: "Authenticated Successfully",
} as const;

export const metadata = {
  title: "Search",
  description: "Find vehicles on reantals and filter to match your needs.",
  openGraph: {
    title: "Search",
    description: "Find vehicles on reantals and filter to match your needs.",
    type: "website",
  },
};

export const carListings = [
  {
    _id: "766e174b09e84ea0ad13d8ab0e0feff3",
    id: "766e174b09e84ea0ad13d8ab0e0feff3",
    createdAt: "2025-10-30T00:00:00.000Z",
    updatedAt: null,
    createdBy: "admin",
    updatedBy: null,
    vendorId: "vendor_001",
    vendorSnapshot: {
      name: "AutoNation Ghana",
      contact: "+233200000001",
      rating: 4.9,
    },
    title: "Toyota Camry 2025",
    description:
      "The 2025 Camry ushers in a new era for Toyota’s midsize sedan: it transitions to an all-hybrid powertrain in many markets, giving up traditional petrol engines for greater efficiency. It retains the comfort, build quality, and reliability the Camry is known for.",
    price: 400000,
    category: "Car",
    city: "Accra",
    region: "Greater Accra",
    status: "Pending",
    images: [Corolla, Corolla, Camaro],
    reviewMemo: "",
    reviewedBy: "",
    make: "Toyota",
    model: "Camry",
    year: "2025",
    condition: "Brand New",
    mileage: "10",
    transmission: "Automatic",
    fuelType: "Hybrid",
    identificationNumber: "7707894748i347y8u39834y4ui4",
    features: [
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Central Locking",
      "Sunroof/Moonroof",
      "Leather Seats",
      "Navigation System",
      "Backup Camera",
      "Parking Sensors",
      "Bluetooth",
      "Apple CarPlay",
      "Android Auto",
      "Cruise Control",
      "Keyless Entry",
      "Alloy reantals",
      "Fog Lights",
    ],
    color: "Gray",
    seatingCapacity: "5",
    warranty: "Manufacturer Warranty",
    inspectionAllowed: "Yes",
    availabilityStatus: "Available",
    __v: 0,
  },
  {
    _id: "3162233492d649268f15d743c24d669e",
    id: "3162233492d649268f15d743c24d669e",
    createdAt: "2025-10-30T00:00:00.000Z",
    updatedAt: null,
    createdBy: "admin",
    updatedBy: null,
    vendorId: "vendor_002",
    vendorSnapshot: {
      name: "Elite Motors Ghana",
      contact: "+233200000002",
      rating: 4.8,
    },
    title: "Toyota Camry 2024",
    description:
      "The 2024 Toyota Camry blends practicality with refined design and hybrid efficiency. Its smooth ride, safety tech, and reliability make it perfect for both urban and long-distance travel.",
    price: 380000,
    category: "Car",
    city: "Accra",
    region: "Greater Accra",
    status: "Pending",
    images: [Corolla, Corolla, Camaro],
    reviewMemo: "",
    reviewedBy: "",
    make: "Toyota",
    model: "Camry",
    year: "2024",
    condition: "Brand New",
    mileage: "15",
    transmission: "Automatic",
    fuelType: "Petrol / Hybrid",
    identificationNumber: "7707894748i347y8u39834y4ui5",
    features: [
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Central Locking",
      "Leather Seats",
      "Backup Camera",
      "Parking Sensors",
      "Bluetooth",
      "Cruise Control",
      "Keyless Entry",
      "Apple CarPlay",
      "Android Auto",
      "Alloy reantals",
    ],
    color: "White",
    seatingCapacity: "5",
    warranty: "Manufacturer Warranty",
    inspectionAllowed: "Yes",
    availabilityStatus: "Available",
    __v: 0,
  },
  {
    _id: "abc394d4d4154469918d31c789d44556",
    id: "abc394d4d4154469918d31c789d44556",
    createdAt: "2025-10-30T00:00:00.000Z",
    updatedAt: null,
    createdBy: "admin",
    updatedBy: null,
    vendorId: "vendor_003",
    vendorSnapshot: {
      name: "Honda Center Ghana",
      contact: "+233200000003",
      rating: 4.7,
    },
    title: "Honda Civic 2024",
    description:
      "The 2024 Honda Civic combines sleek design, agile handling, and top-tier safety features. Efficient and practical, it remains a class-leading compact sedan.",
    price: 360000,
    category: "Car",
    city: "Accra",
    region: "Greater Accra",
    status: "Pending",
    images: [Corolla, Corolla, Corolla],
    reviewMemo: "",
    reviewedBy: "",
    make: "Honda",
    model: "Civic",
    year: "2024",
    condition: "Brand New",
    mileage: "10",
    transmission: "Automatic",
    fuelType: "Petrol",
    identificationNumber: "7738894748h347y8u39834y4ui6",
    features: [
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Leather Seats",
      "Navigation System",
      "Adaptive Cruise Control",
      "Backup Camera",
      "Apple CarPlay",
      "Android Auto",
      "Lane Departure Warning",
    ],
    color: "Silver",
    seatingCapacity: "5",
    warranty: "Manufacturer Warranty",
    inspectionAllowed: "Yes",
    availabilityStatus: "Available",
    __v: 0,
  },
  {
    _id: "c36b4b091b4748a294fba7637e25ffe5",
    id: "c36b4b091b4748a294fba7637e25ffe5",
    createdAt: "2025-10-30T00:00:00.000Z",
    updatedAt: null,
    createdBy: "admin",
    updatedBy: null,
    vendorId: "vendor_004",
    vendorSnapshot: {
      name: "Tesla Ghana",
      contact: "+233200000004",
      rating: 5.0,
    },
    title: "Tesla Model 3 2024",
    description:
      "The 2024 Tesla Model 3 delivers a futuristic driving experience with silent performance, enhanced range, and a minimalist tech-focused interior.",
    price: 580000,
    category: "Car",
    city: "Accra",
    region: "Greater Accra",
    status: "Pending",
    images: [Corolla, Corolla, Corolla],
    reviewMemo: "",
    reviewedBy: "",
    make: "Tesla",
    model: "Model 3",
    year: "2024",
    condition: "Brand New",
    mileage: "5",
    transmission: "Automatic",
    fuelType: "Electric",
    identificationNumber: "7799894748t347y8u39834y4ui8",
    features: [
      "Autopilot",
      "Wireless Charging",
      "Heated Seats",
      "Panoramic Glass Roof",
      "Apple CarPlay (Beta)",
      "Android Auto (Beta)",
      "Adaptive Cruise Control",
      "Keyless Entry",
      "Blind Spot Monitoring",
    ],
    color: "Pearl White",
    seatingCapacity: "5",
    warranty: "Manufacturer Warranty",
    inspectionAllowed: "Yes",
    availabilityStatus: "Available",
    __v: 0,
  },
];
